
services:
  go-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./public:/app/public
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Configuração do Nginx
      - ./public:/usr/share/nginx/html/public  # Servindo arquivos estáticos
    depends_on:
      - go-app
    restart: always
