name: deploy-server
on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Deploy to server
              uses: easingthemes/ssh-deploy@main
              with: 
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                ARGS: "-rlgoDzvc -i"
                REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                REMOTE_USER: ${{ secrets.REMOTE_USER }}
                TARGET: ${{ secrets.REMOTE_TARGET }}
                SOURCE: "."
                SCRIPT_AFTER: |
                    ls -al
                    docker compose up --build -d